### ISSUE TITLE
Typo report

### ISSUE THREAD

**Issue by garthlei** [pku-compiler-design-spring/CompilerProject-2020Spring#5]
I have found two minor typos in the original code:
In the function signature in project1/kernels/kernel_case8.cc, the "&Be" should be "&B".
At line 14 of project2/clean/clean2.cc, the "(&A)" should be "(&dA)", according to other files.

These typos do not affect much, but they can bring git modification messages after we use "make clean"…

**Comment by KnowingNothing** [comment]
Thank you for pointing out the typos.
For the first typo, I think it should be fixed before. You can check the new code.
For the second typo, do you mean the grad_case1 ? I have checked in a fix for it.

**Comment by garthlei** [comment]
Thanks for your reply.
For the first typo, I just checked the code of project1/kernels/kernel_case8.cc on the GitHub website of the repo, and it showed "&Be" at line 3, so I guess this have not been fixed yet.
For the second one, this is exactly what I meant, and now it has now been fixed.

**Comment by KnowingNothing** [comment]
I see. The fix is not enabled because .gitignore refuses to update the files in kernels/ folder. I forced the fix just now.
